### ISSUE TITLE
通话录音对方的声音很小

### ISSUE THREAD

**Issue by introspection3** [servbus/cordova-plugin-audio-recorder-api#1]
通话录音对方的声音很小

**Comment by cnryb** [comment]
你给的信息实在是太少了。 
请提供些更详细的信息。
比如你用的是哪种系统的呀，怎么做的通话录音呀，等等。
最好能给个异常的例子，便于在我的开发环境中还原出你所遇到的异常情况。

**Comment by ryanlin1986** [comment]
应该说的是录音停止以后，没有重置状态，导致播放声音的时候很轻， 重启App声音恢复正常

**Comment by cnryb** [comment]
1、哪个平台，iOS还是Android
2、重置什么状态后会正常
3、怎么来播放的，播放里面有没有控制音量的东西

**Comment by ryanlin1986** [comment]
ios, 录音结束的时候加上以下语句解决：
  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionDuckOthers error:nil];
  [[AVAudioSession sharedInstance] setActive:NO error:nil];

**Comment by cnryb** [comment]
非常感谢你的反馈，我们暂时还没有碰到这个问题。
希望这个 issue 能帮助到需要的人。
